# `swagger.yaml` file contents
swagger: '2.0'
info:
  title: connextion api stub
  version: "0.2"
  description: simple example of connextion
consumes:
  - application/json
produces:
  - application/json
paths:
  /string-length:
    get:
      operationId: api.string_length
      summary: how long is a string?
      parameters:
        - name: body
          in: query
          type: string
          required: true
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              length:
                type: integer
                example: 10
                description: character count
