# `swagger.yaml` file contents
swagger: '2.0'
info:
  title: connextion api stub
  version: "0.2"
  description: simple example of connextion
consumes:
  - application/json
produces:
  - application/json
paths:

  /string-length:
    get:
      operationId: api.string_length
      summary: how long is a string?
      parameters:
        - $ref: '#/parameters/body'
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              length:
                type: integer
                example: 10
                description: character count

  /string-info:
    get:
      operationId: api.string_info
      summary: what about a string? defaults to length.
      parameters:
        - $ref: '#/parameters/body'
        - name: include_whitespace
          in: query
          type: boolean
          required: false
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              length:
                type: integer
                example: 10
                description: length of string
              include_whitespace:
                type: boolean
                example: true
                description: include whitespace or not
              body:
                type: string
                example: "a string"
                description: string that is measured

parameters:
# not very useful.  This is for passing data objects around
# will I ever resuse this?  Well, just an example of format
# I reuse body so give it a try
  body:
    name: body
    in: query
    type: string
    required: true
